theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
true-color = true
color-modes = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
